
/**
	Finds a level in act 1.
	@param stageNum [int] the number of the stage, like 1 or 2
	@return [Level]
*/
function getAct1Level(stageNum){
	var background = 'grass';
	var stuffOnGrid;
	var preferredAllyPlacement;
	var startDialogues = [];
	
	switch(stageNum){
	case 1:
		stuffOnGrid = [
				makeObstacle(7,11,"house"),
				makeObstacle(6,10,"tree"),
				makeObstacle(8,10,"tree"),
				makeObstacle(6,9,"tree"),
				makeObstacle(8,9,"tree"),
				makeObstacle(6,8,"tree"),
				makeObstacle(8,8,"tree"),
				makeObstacle(6,7,"tree"),
				makeObstacle(8,7,"tree"),
				makeSteppable(7,10,"path"),
				makeSteppable(7,9,"path"),
				makeSteppable(7,8,"path"),
				makeSteppable(7,7,"path"),
				makeObstacle(6,6,"tree"),
				makeObstacle(8,6,"tree"),
				makeSteppable(7,6,"path"),
				makeSteppable(7,5,"path"),
				makeSteppable(7,4,"path"),
				makeSteppable(7,3,"path"),
				makeSteppable(7,2,"path"),
				makeSteppable(7,1,"path"),
				makeSteppable(7,0,"path"),
				makeEnemy("Squirrel",7,7,1,0),
				];
		preferredAllyPlacement = [
			[7,8],
			[7,8],
			[7,8],
			[7,8],
			[7,8],
		];
		
		startDialogues = [
			makeHathixDialogue("Let me see... the only way to East Sprinklestan is by boat.\
			The city of Albucreamy has a big harbor, so it should have a ship going there. According to my map Albucreamy is just northeast of here..."),
			makeEnemyDialogue('Squirrel',"So where do you think YOU'RE going, huh, punk?"),
			makeHathixDialogue("What?! I can't even go past my front door without being attacked! Gah. Guess I better beat this guy up\
			. First click on me to select me, and then click on the up attack button to attack the squirrel until it dies."),
		];
		
		break;
	case 2:
		stuffOnGrid = [
			makeSteppable(7,14,"path"),
			makeSteppable(7,13,"path"),
			makeSteppable(7,12,"path"),
			makeSteppable(7,11,"path"),
			makeSteppable(7,10,"path"),
			makeSteppable(7,9,"path"),
			makeSteppable(7,8,"path"),
			makeObstacle(6,8,"house"),
			makeObstacle(6,7,"house2"),
			makeObstacle(8,7,"house3"),
			makeObstacle(8,8,"house2"),
			makeObstacle(8,6,"house2"),
			makeObstacle(6,6,"house"),
			makeObstacle(5,7,"house3"),
			makeObstacle(9,7,"house"),
			makeObstacle(11,7,"tree"),
			makeObstacle(3,7,"tree"),
			makeObstacle(3,6,"tree"),
			makeObstacle(3,8,"tree"),
			makeObstacle(11,6,"tree"),
			makeObstacle(11,8,"tree"),
			makeObstacle(4,5,"tree"),
			makeObstacle(10,5,"tree"),
			makeSteppable(7,7,"path"),
			makeSteppable(7,6,"path"),
			makeSteppable(7,5,"path"),
			makeSteppable(6,4,"path"),
			makeSteppable(5,3,"path"),
			makeSteppable(4,2,"path"),
			makeSteppable(4,1,"path"),
			makeSteppable(4,0,"path"),
			makeObstacle(5,2,"house"),
			makeEnemy("Squirrel",7,7,1,0),
			makeEnemy("Squirrel",6,5,1,0),
			makeEnemy("Squirrel",7,8,1,0),		
			];
		preferredAllyPlacement = [
			[7,14],
			[7,14],
			[7,14],
			[7,14],
			[7,14],		
		];
		startDialogues = [
			makeHathixDialogue("It's a huge swarm of squirrels... I should go up to them. Click on me and use the move arrow buttons\
			(or the arrow keys) to move me. And use the attack arrow buttons (or w/a/s/d) to attack once I'm adjacent to a squirrel."),
		];
		break;
	case 3:
		stuffOnGrid = [
			makeEnemy("Squirrel",5,3,1),
			makeSteppable(2,14,"path"),
			makeSteppable(2,13,"path"),
			makeSteppable(2,12,"path"),
			makeSteppable(3,11,"path"),
			makeSteppable(4,10,"path"),
			makeSteppable(5,9,"path"),
			makeSteppable(6,8,"path"),
			makeSteppable(7,7,"path"),
			makeSteppable(8,6,"path"),
			makeSteppable(7,5,"path"),
			makeSteppable(6,4,"path"),
			makeSteppable(5,3,"path"),
			makeSteppable(9,6,"path"),
			makeSteppable(10,6,"path"),
			makeSteppable(11,6,"path"),
			makeSteppable(12,6,"path"),
			makeSteppable(13,6,"path"),
			makeSteppable(14,6,"path"),
			makeEnemy("Cow",6,8,1,1),
			makeEnemy("Squirrel",14,6,2),
			makeObstacle(14,5,"tree"),
			makeObstacle(13,5,"tree"),
			makeObstacle(13,7,"tree"),
			makeObstacle(14,7,"tree"),
			makeObstacle(12,5,"tree"),
			makeObstacle(12,7,"tree"),
			makeObstacle(8,7,"house"),
			makeObstacle(4,2,"house"),
			makeObstacle(14,8,"tree"),
			makeObstacle(14,4,"tree"),
			makeObstacle(13,4,"tree"),
			makeObstacle(13,8,"tree"),
			makeObstacle(14,9,"tree"),
			makeObstacle(14,3,"tree"),		
			makeHeart(8,8,"half"),			
			];
		preferredAllyPlacement = [
			[2,12],
			[2,12],
			[2,12],
			[2,12],
			[2,12],		
		];
		startDialogues = [
			makeHathixDialogue("Wait, I think I know that cow. So why is he fighting against me?"),
			makeEnemyDialogue("Cow","Oh, hey, hathix. I'm just fighting you because Llama pays so well. If you beat me,\
			then I can join you."),
			makeEnemyDialogue("Cow","Once I join you, you can switch between us by clicking on us."),
		];
		break;
	case 4:
		stuffOnGrid = [
			makeHeart(9,6,"half"),
			makeSteppable(4,14,"path"),
			makeSteppable(4,13,"path"),
			makeSteppable(4,12,"path"),
			makeSteppable(4,11,"path"),
			makeSteppable(4,10,"path"),
			makeSteppable(4,9,"path"),
			makeSteppable(5,9,"path"),
			makeSteppable(6,9,"path"),
			makeSteppable(7,9,"path"),
			makeSteppable(8,9,"path"),
			makeSteppable(9,9,"path"),
			makeSteppable(9,8,"path"),
			makeSteppable(9,7,"path"),
			makeSteppable(9,6,"path"),
			makeSteppable(10,6,"path"),
			makeSteppable(11,6,"path"),
			makeSteppable(12,6,"path"),
			makeSteppable(13,6,"path"),
			makeSteppable(14,6,"path"),
			makeSteppable(10,9,"dirt"),
			makeSteppable(10,10,"dirt"),
			makeSteppable(10,11,"dirt"),
			makeObstacle(10,12,"house3"),
			makeObstacle(11,11,"house2"),
			makeEnemy("Cow",11,12,1),
			makeEnemy("Squirrel",12,1,2),
			makeObstacle(9,11,"tree"),
			makeObstacle(8,5,"tree"),
			makeObstacle(9,5,"tree"),
			makeObstacle(8,6,"tree"),
			makeObstacle(14,5,"tree"),
			makeObstacle(14,7,"tree"),
			makeObstacle(10,8,"hydrant"),
			makeObstacle(3,12,"hydrant"),
			makeEnemy("Squirrel",5,13,1),
			makeEnemy("Squirrel",3,1,1),
			makeSteppable(6,8,"dirt"),
			makeObstacle(6,7,"house"),
			makeObstacle(7,8,"hydrant"),		
		];
		preferredAllyPlacement = [
			[4,14],
			[3,14],
			[5,14],
			[6,14],
			[2,14],		
		];
		startDialogues = [
			makeHathixDialogue("Phew, I'm tired. And look at all those enemies..."),
			makeEnemyDialogue('Squirrel',"You want our heart, huh? Well come get it! Hehehe!"),
			makeHathixDialogue("Looks like that heart over there will heal half of anyone's health. Better go get it."),
		];
		break;
	case 5:
		stuffOnGrid = [
			makeObstacle(0,4,"tree"),
			makeObstacle(0,6,"tree"),
			makeObstacle(1,7,"tree"),
			makeObstacle(2,8,"tree"),
			makeObstacle(2,6,"tree"),
			makeObstacle(2,4,"tree"),
			makeObstacle(1,3,"tree"),
			makeObstacle(2,2,"tree"),
			makeObstacle(2,3,"tree"),
			makeObstacle(2,7,"tree"),
			makeObstacle(3,6,"tree"),
			makeObstacle(3,4,"tree"),
			makeObstacle(4,4,"tree"),
			makeObstacle(4,6,"tree"),
			makeObstacle(5,4,"tree"),
			makeObstacle(5,6,"tree"),
			makeHeart(0,5,"full"),
			makeHeart(14,14,"quarter"),
			makeHeart(14,0,"quarter"),
			makeObstacle(6,4,"tree"),
			makeObstacle(6,6,"tree"),
			makeEnemy("Squirrel",10,1,2),
			makeEnemy("Squirrel",8,5,1),
			makeEnemy("Pig",5,9,1,0.5),
			makeEnemy("Cow",11,13,1),
			makeEnemy("Squirrel",11,8,2),
			makeObstacle(12,3,"tree"),
			makeObstacle(7,12,"tree"),
			makeObstacle(4,1,"tree"),
			makeObstacle(1,11,"tree"),
			makeObstacle(3,14,"tree"),
			makeObstacle(11,10,"tree"),
			makeObstacle(9,7,"tree"),
			makeObstacle(13,13,"tree"),
			makeObstacle(14,13,"tree"),
			makeObstacle(12,12,"tree"),
			makeObstacle(11,12,"tree"),
		];
		preferredAllyPlacement = [
			[3,5],
			[2,5],
			[1,5],
			[1,6],
			[1,4],		
		];
		startDialogues = [
			makeHathixDialogue("Hmm... OK, according to my map, we're on our way to Albucreamy.\
			Just need to get through this forest and then it's pretty easy going."),
			makeEnemyDialogue('Pig',"Hold up! This is an ambush!"),
			makeHathixDialogue("Wait, if it's an ambush, aren't you not supposed to tell us about it?"),
			makeEnemyDialogue('Pig','Good point. Er, uh, could you pretend you didn\'t hear that?'),
			makeHathixDialogue("Whatever. We should spread out to take on all the enemies. There are hearts around here if we need them."),
			makeEnemyDialogue('Pig','I kinda have to agree with you. Everyone, go get \'em!'),
		];
		break;
	case 6:
		stuffOnGrid = [
			makeSteppable(0,3,"path"),
			makeSteppable(1,3,"path"),
			makeSteppable(2,3,"path"),
			makeSteppable(3,3,"path"),
			makeSteppable(4,3,"path"),
			makeSteppable(5,3,"path"),
			makeSteppable(5,4,"path"),
			makeSteppable(5,5,"path"),
			makeObstacle(2,2,"sign"),
			makeSteppable(5,6,"sidewalk"),
			makeSteppable(4,6,"sidewalk"),
			makeSteppable(6,6,"sidewalk"),
			makeSteppable(4,7,"sidewalk"),
			makeSteppable(5,7,"sidewalk"),
			makeSteppable(6,7,"sidewalk"),
			makeSteppable(4,8,"sidewalk"),
			makeSteppable(5,8,"sidewalk"),
			makeSteppable(6,8,"sidewalk"),
			makeSteppable(4,9,"sidewalk"),
			makeSteppable(5,9,"sidewalk"),
			makeSteppable(6,9,"sidewalk"),
			makeSteppable(4,10,"sidewalk"),
			makeSteppable(5,10,"sidewalk"),
			makeSteppable(6,10,"sidewalk"),
			makeSteppable(4,11,"sidewalk"),
			makeSteppable(5,11,"sidewalk"),
			makeSteppable(6,11,"sidewalk"),
			makeSteppable(4,12,"sidewalk"),
			makeSteppable(5,12,"sidewalk"),
			makeSteppable(6,12,"sidewalk"),
			makeSteppable(4,13,"sidewalk"),
			makeSteppable(5,13,"sidewalk"),
			makeSteppable(6,13,"sidewalk"),
			makeSteppable(4,14,"sidewalk"),
			makeSteppable(5,14,"sidewalk"),
			makeSteppable(6,14,"sidewalk"),
			makeObstacle(5,7,"hotel"),
			makeObstacle(5,9,"tree"),
			makeObstacle(5,10,"tree"),
			makeObstacle(5,11,"tree"),
			makeObstacle(3,11,"shop"),
			makeObstacle(7,14,"building"),
			makeObstacle(3,14,"shop"),
			makeObstacle(7,6,"house2"),
			makeObstacle(3,9,"house2"),
			makeSteppable(7,11,"sidewalk"),
			makeSteppable(8,11,"sidewalk"),
			makeSteppable(9,11,"sidewalk"),
			makeSteppable(10,11,"sidewalk"),
			makeSteppable(11,11,"sidewalk"),
			makeSteppable(12,11,"sidewalk"),
			makeSteppable(13,11,"sidewalk"),
			makeSteppable(14,11,"sidewalk"),
			makeObstacle(14,10,"house3"),
			makeObstacle(14,12,"house2"),
			makeObstacle(13,10,"building"),
			makeObstacle(13,12,"house"),
			makeObstacle(12,12,"hydrant"),
			makeObstacle(10,10,"tree"),
			makeSteppable(6,3,"path"),
			makeSteppable(7,3,"path"),
			makeSteppable(8,3,"path"),
			makeSteppable(9,3,"path"),
			makeSteppable(10,3,"path"),
			makeSteppable(11,3,"path"),
			makeSteppable(12,3,"path"),
			makeSteppable(13,3,"path"),
			makeSteppable(14,3,"path"),
			makeObstacle(7,10,"house"),
			makeObstacle(7,12,"house3"),
			makeObstacle(3,13,"shop"),
			makeObstacle(3,6,"house2"),
			makeEnemy("Pig",13,11,2),
			makeEnemy("Squirrel",3,12,2),
			makeEnemy("Sheep",13,3,1,0.5),
			makeEnemy("Sheep",8,14,1),
			makeEnemy("Squirrel",11,6,2),	
			makeHeart(5,8,'half'),
			makeHeart(14,11,'half'),
			makeHeart(7,3,'quarter'),
		];
		preferredAllyPlacement = [
			[2,3],
			[1,3],
			[1,2],
			[1,4],
			[0,3],		
		];
		startDialogues = [
			makeSignDialogue("Welcome to Albucreamy! Population 15,000."),
			makeHathixDialogue("Phew, we're finally here. But how can we find a boat out of here?"),
			makeBystanderDialogue('Panda','Oh, hey kids. Albucreamy is a seaside town; the dock\'s at the far side of town.'),
			makeBystanderDialogue('Panda','And, by the way, look out for those sheep. They may look cute but they\'re really fierce.'),
		];
		break;
	case 7:
		background = 'sidewalk';
		stuffOnGrid = [
			makeObstacle(10,8,"tree"),
			makeObstacle(11,8,"tree"),
			makeObstacle(10,9,"tree"),
			makeObstacle(10,10,"tree"),
			makeObstacle(11,10,"tree"),
			makeObstacle(12,8,"tree"),
			makeObstacle(12,10,"tree"),
			makeHeart(11,9,"half"),
			makeObstacle(1,1,"tree"),
			makeObstacle(2,1,"tree"),
			makeObstacle(3,1,"tree"),
			makeObstacle(3,2,"tree"),
			makeObstacle(3,3,"tree"),
			makeObstacle(2,3,"tree"),
			makeObstacle(1,3,"tree"),
			makeHeart(2,2,"half"),
			makeObstacle(8,14,"sign"),
			makeObstacle(10,1,"shop"),
			makeObstacle(10,3,"shop"),
			makeObstacle(10,2,"shop"),
			makeObstacle(10,5,"shop"),
			makeObstacle(10,6,"shop"),
			makeObstacle(10,7,"shop"),
			makeEnemy("Sheep",8,5,1),
			makeEnemy("Pig",6,7,2),
			makeEnemy("Cow",4,5,1),
			makeEnemy("Squirrel",6,3,2),
			makeEnemy("Sheep",14,4,2),
			makeObstacle(2,11,"house3"),
			makeObstacle(1,11,"house2"),
			makeObstacle(2,12,"house"),
			makeObstacle(1,12,"house"),
			makeObstacle(0,11,"house3"),
			makeObstacle(0,12,"house2"),
			makeObstacle(0,13,"house"),
			makeObstacle(1,13,"house3"),
			makeEnemy("Pig",2,13,2),
			makeObstacle(2,6,"building"),
			makeObstacle(2,7,"building"),
			makeObstacle(2,8,"building"),
			makeObstacle(2,9,"building"),
			makeObstacle(2,10,"building"),
			makeObstacle(10,11,"hotel"),
			makeObstacle(11,11,"building"),
			makeObstacle(11,12,"bank"),
			makeObstacle(10,12,"hotel"),
			makeObstacle(10,13,"building"),
			makeObstacle(11,13,"house"),
			makeObstacle(12,12,"house"),
			makeObstacle(12,13,"house3"),
			makeEnemy("Cow",12,11,1),
			makeObstacle(5,11,"house"),
			makeObstacle(6,11,"building"),
			makeObstacle(7,11,"shop"),
			makeHeart(8,13,"quarter"),
			makeHeart(1,10,"quarter"),	
			makeSteppable(10,8,"grass"),
			makeSteppable(11,8,"grass"),
			makeSteppable(12,8,"grass"),
			makeSteppable(10,9,"grass"),
			makeSteppable(11,9,"grass"),
			makeSteppable(12,9,"grass"),
			makeSteppable(10,10,"grass"),
			makeSteppable(11,10,"grass"),
			makeSteppable(12,10,"grass"),
			makeSteppable(1,1,"grass"),
			makeSteppable(2,1,"grass"),
			makeSteppable(3,1,"grass"),
			makeSteppable(1,2,"grass"),
			makeSteppable(2,2,"grass"),
			makeSteppable(3,2,"grass"),
			makeSteppable(1,3,"grass"),
			makeSteppable(2,3,"grass"),
			makeSteppable(3,3,"grass"),			
		];
		preferredAllyPlacement = [
			[6,5],
			[6,4],
			[7,5],
			[6,6],
			[5,5],		
		];
		startDialogues = [];
		break;
	case 8:
		background = 'sidewalk';
		stuffOnGrid = [
			makeObstacle(14,5,"water"),
			makeObstacle(13,5,"water"),
			makeObstacle(12,6,"water"),
			makeObstacle(11,8,"water"),
			makeObstacle(11,7,"water"),
			makeObstacle(12,9,"water"),
			makeObstacle(13,10,"water"),
			makeObstacle(13,11,"water"),
			makeObstacle(12,12,"water"),
			makeObstacle(11,13,"water"),
			makeObstacle(10,13,"water"),
			makeObstacle(9,13,"water"),
			makeObstacle(8,14,"water"),
			makeObstacle(12,5,"water"),
			makeObstacle(11,6,"water"),
			makeObstacle(13,6,"water"),
			makeSteppable(9,10,"bridge"),
			makeObstacle(10,10,"water"),
			makeSteppable(9,11,"bridge"),
			makeSteppable(9,12,"bridge"),
			makeSteppable(9,9,"bridge"),
			makeObstacle(8,9,"water"),
			makeObstacle(8,10,"water"),
			makeObstacle(8,11,"water"),
			makeObstacle(8,12,"water"),
			makeObstacle(8,13,"water"),
			makeObstacle(11,9,"water"),
			makeObstacle(10,9,"water"),
			makeObstacle(12,7,"water"),
			makeObstacle(12,8,"water"),
			makeObstacle(13,7,"water"),
			makeObstacle(14,6,"water"),
			makeObstacle(14,7,"water"),
			makeObstacle(13,8,"water"),
			makeObstacle(14,8,"water"),
			makeObstacle(13,9,"water"),
			makeObstacle(14,9,"water"),
			makeObstacle(14,10,"water"),
			makeObstacle(14,11,"water"),
			makeObstacle(13,12,"water"),
			makeObstacle(14,12,"water"),
			makeObstacle(9,14,"water"),
			makeObstacle(10,14,"water"),
			makeObstacle(11,14,"water"),
			makeObstacle(12,13,"water"),
			makeObstacle(14,14,"water"),
			makeObstacle(14,13,"water"),
			makeObstacle(7,11,"water"),
			makeObstacle(7,12,"water"),
			makeObstacle(7,13,"water"),
			makeObstacle(7,14,"water"),
			makeObstacle(6,14,"water"),
			makeObstacle(6,13,"water"),
			makeObstacle(5,14,"water"),
			makeObstacle(10,8,"water"),
			makeObstacle(8,8,"water"),
			makeObstacle(13,4,"water"),
			makeSteppable(11,10,"grass"),
			makeSteppable(12,10,"grass"),
			makeSteppable(10,11,"grass"),
			makeSteppable(11,11,"grass"),
			makeSteppable(12,11,"grass"),
			makeSteppable(10,12,"grass"),
			makeSteppable(11,12,"grass"),
			makeSteppable(13,13,"grass"),
			makeSteppable(12,14,"grass"),
			makeSteppable(13,14,"grass"),
			makeBoss("Colonel Fried Chicken","Chicken",9,12,5),
			makeObstacle(6,7,"building"),
			makeObstacle(6,8,"building"),
			makeObstacle(6,9,"house3"),
			makeObstacle(6,10,"house"),
			makeObstacle(10,5,"house"),
			makeObstacle(11,4,"house"),
			makeObstacle(12,3,"house2"),
			makeObstacle(13,3,"hydrant"),
			makeSteppable(5,13,"bridge"),
			makeObstacle(4,13,"water"),
			makeObstacle(4,14,"water"),
			makeHeart(5,13,"half"),
			makeHeart(12,10,"full"),
			makeObstacle(1,4,"tree"),
			makeObstacle(2,4,"tree"),
			makeObstacle(1,5,"tree"),
			makeObstacle(2,5,"tree"),
			makeObstacle(2,10,"house"),
			makeObstacle(11,1,"house2"),
			makeObstacle(0,0,"bank"),
			makeObstacle(0,1,"hotel"),
			makeObstacle(1,0,"building"),
			makeObstacle(12,1,"house3"),
			makeObstacle(13,1,"house"),
			makeHeart(14,2,"half"),		
		];
		preferredAllyPlacement = [
			[6,3],
			[5,3],
			[6,2],
			[5,4],
			[7,2],		
		];
		startDialogues = [
			makeSignDialogue("Next ship to East Sprinklestan leaves at 10:30."),
			makeHathixDialogue("Well, there's the harbor. And it's 10:20, so we're just in time."),
			makeBossDialogue('Colonel Fried Chicken','Chicken',"Soldiers, at attention! Wait... where'd ya go?\
			Don't tell me my entire elite squadron of warrior chickens has deserted me..."),
			makeHathixDialogue("I'm sorry to hear that, Colonel."),
			makeBossDialogue('Colonel Fried Chicken','Chicken',"Yeah, most people are. But where was I? Oh yeah,\
			Llama's paid me to make sure you don't board this ship. So I guess I'll have to kill you."),
		];
		break;
	} //end switch
	
	return new Level('1-' + stageNum,background,stuffOnGrid,preferredAllyPlacement,startDialogues);	
}